# Generated by Django 4.2.4 on 2023-10-12 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('passenger_capacity', models.PositiveSmallIntegerField()),
                ('cargo_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='vehicles/')),
            ],
        ),
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='select car model', max_length=100)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
