# Generated by Django 4.2.4 on 2023-10-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_ridebooking_email_ridebooking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebooking',
            name='email',
            field=models.CharField(default='Your Email here', max_length=255),
        ),
    ]
